security:
  basic:
    enabled: true               # 开启基于HTTP basic的认证
  user:
    name: pactera                  # 配置登录的账号是pactera
    password: pactera       # 配置登录的密码是pactera
server:
  port: 8761                    # 指定该Eureka实例的端口
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/