server:
  port: 8000
spring:
  application:
    name: pactera-consumer-account
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true